// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HeaderMenuController from "./header_menu_controller"
application.register("header-menu", HeaderMenuController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
